### ISSUE TITLE
seachindict.py does not work as expected

### ISSUE THREAD

**Issue by murpholinox** [Serulab/Py4Bio#2]
```
[murphy@eva02 ch4]$ python3 seachindict.py 
Traceback (most recent call last):
  File "seachindict.py", line 4, in <module>
    print(color_code[name])
TypeError: list indices must be integers or slices, not str
[murphy@eva02 ch4]$ cat seachindict.py 
color_code = [('red',1), ('green',2), ('blue',3), ('black',4)]
name = 'blue'
color_code_d = dict(color_code)
print(color_code[name])
[murphy@eva02 ch4]$ python
Python 3.7.4 (default, Aug 12 2019, 14:45:07) 
[GCC 9.1.1 20190605 (Red Hat 9.1.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> color_code = [('red',1), ('green',2), ('blue',3), ('black',4)]
>>> name = 'blue'
>>> color_code_d = dict(color_code)
>>> print(color_code[name])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list indices must be integers or slices, not str
```

**Comment by sbassi** [comment]
Fixed the code, thank you!
